// V11 fresh D1 installer: generated from migrations; no DB.exec / no PRAGMA.
export const V11_SCHEMA_STAGES = [
  {
    "name": "0001_initial",
    "statements": [
      "CREATE TABLE IF NOT EXISTS counters (\n  key TEXT PRIMARY KEY,\n  value INTEGER NOT NULL DEFAULT 0\n);",
      "INSERT OR IGNORE INTO counters(key,value) VALUES('sfn_user',0);",
      "CREATE TABLE IF NOT EXISTS users (\n  id TEXT PRIMARY KEY,\n  sfn_no INTEGER NOT NULL UNIQUE CHECK(sfn_no BETWEEN 1 AND 10000),\n  sfn_id TEXT NOT NULL UNIQUE,\n  full_name TEXT NOT NULL,\n  email TEXT NOT NULL UNIQUE,\n  phone TEXT NOT NULL DEFAULT '',\n  role TEXT NOT NULL DEFAULT 'student',\n  status TEXT NOT NULL DEFAULT 'pending_activation',\n  avatar_key TEXT,\n  profile_json TEXT NOT NULL DEFAULT '{}',\n  password_hash TEXT NOT NULL DEFAULT '',\n  password_salt TEXT NOT NULL DEFAULT '',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);",
      "CREATE INDEX IF NOT EXISTS idx_users_role ON users(role,status);",
      "CREATE TRIGGER IF NOT EXISTS trg_users_max_10000\nBEFORE INSERT ON users\nWHEN (SELECT COUNT(*) FROM users) >= 10000\nBEGIN\n  SELECT RAISE(ABORT, 'SFN_ACCOUNT_LIMIT_10000');\nEND;",
      "CREATE TABLE IF NOT EXISTS account_requests (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  request_code TEXT NOT NULL UNIQUE,\n  full_name TEXT NOT NULL,\n  email TEXT NOT NULL,\n  phone TEXT NOT NULL,\n  data_json TEXT NOT NULL DEFAULT '{}',\n  portrait_key TEXT NOT NULL,\n  student_card_key TEXT,\n  status TEXT NOT NULL DEFAULT 'pending',\n  reviewed_by TEXT,\n  reviewed_at TEXT,\n  approved_user_id TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "CREATE INDEX IF NOT EXISTS idx_account_requests_status ON account_requests(status,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS activation_tokens (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  token TEXT NOT NULL UNIQUE,\n  user_id TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  used_at TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE TABLE IF NOT EXISTS sessions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  token TEXT NOT NULL UNIQUE,\n  user_id TEXT NOT NULL,\n  ip_hash TEXT NOT NULL DEFAULT '',\n  user_agent TEXT NOT NULL DEFAULT '',\n  expires_at TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id,expires_at DESC);",
      "CREATE TABLE IF NOT EXISTS files (\n  id TEXT PRIMARY KEY,\n  owner_user_id TEXT,\n  r2_key TEXT NOT NULL UNIQUE,\n  name TEXT NOT NULL,\n  mime TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  visibility TEXT NOT NULL DEFAULT 'private',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE INDEX IF NOT EXISTS idx_files_owner ON files(owner_user_id,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS classes (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  description TEXT NOT NULL DEFAULT '',\n  unit TEXT NOT NULL DEFAULT '',\n  cover_key TEXT,\n  join_code TEXT NOT NULL UNIQUE,\n  owner_user_id TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE TABLE IF NOT EXISTS class_members (\n  class_id TEXT NOT NULL,\n  user_id TEXT NOT NULL,\n  role TEXT NOT NULL DEFAULT 'student',\n  status TEXT NOT NULL DEFAULT 'active',\n  joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY(class_id,user_id),\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_class_members_user ON class_members(user_id,status);",
      "CREATE TABLE IF NOT EXISTS class_posts (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  author_user_id TEXT NOT NULL,\n  body TEXT NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE TABLE IF NOT EXISTS materials (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  file_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  description TEXT NOT NULL DEFAULT '',\n  created_by TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE TABLE IF NOT EXISTS assignments (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT 'assignment',\n  title TEXT NOT NULL,\n  instructions TEXT NOT NULL DEFAULT '',\n  due_at TEXT,\n  points REAL NOT NULL DEFAULT 10,\n  created_by TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE TABLE IF NOT EXISTS submissions (\n  id TEXT PRIMARY KEY,\n  assignment_id TEXT NOT NULL,\n  user_id TEXT NOT NULL,\n  text_answer TEXT NOT NULL DEFAULT '',\n  file_id TEXT,\n  status TEXT NOT NULL DEFAULT 'submitted',\n  score REAL,\n  feedback TEXT,\n  submitted_at TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  UNIQUE(assignment_id,user_id),\n  FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE SET NULL\n);",
      "CREATE TABLE IF NOT EXISTS exams (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  instructions TEXT NOT NULL DEFAULT '',\n  duration_minutes INTEGER NOT NULL DEFAULT 30,\n  strict_mode INTEGER NOT NULL DEFAULT 0,\n  question_json TEXT NOT NULL DEFAULT '[]',\n  status TEXT NOT NULL DEFAULT 'draft',\n  created_by TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE TABLE IF NOT EXISTS exam_attempts (\n  id TEXT PRIMARY KEY,\n  exam_id TEXT NOT NULL,\n  user_id TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'in_progress',\n  started_at TEXT,\n  last_saved_at TEXT,\n  submitted_at TEXT,\n  answers_json TEXT NOT NULL DEFAULT '{}',\n  event_log_json TEXT NOT NULL DEFAULT '[]',\n  score REAL,\n  max_score REAL,\n  FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_exam_attempts_user ON exam_attempts(user_id,status,started_at DESC);",
      "CREATE TABLE IF NOT EXISTS live_sessions (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  room_code TEXT NOT NULL UNIQUE,\n  started_by TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'scheduled',\n  scheduled_at TEXT,\n  started_at TEXT,\n  ended_at TEXT,\n  settings_json TEXT NOT NULL DEFAULT '{}',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(started_by) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE TABLE IF NOT EXISTS attendance (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  live_session_id TEXT NOT NULL,\n  user_id TEXT,\n  guest_name TEXT,\n  joined_at TEXT NOT NULL,\n  left_at TEXT,\n  seconds_present INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL DEFAULT 'present',\n  FOREIGN KEY(live_session_id) REFERENCES live_sessions(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE TABLE IF NOT EXISTS support_tickets (\n  id TEXT PRIMARY KEY,\n  ticket_code TEXT NOT NULL UNIQUE,\n  requester_user_id TEXT NOT NULL,\n  category TEXT NOT NULL DEFAULT 'other',\n  subject TEXT NOT NULL,\n  message TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'new',\n  assigned_to TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(requester_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE TABLE IF NOT EXISTS audit_logs (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  actor_user_id TEXT,\n  action TEXT NOT NULL,\n  entity_type TEXT,\n  entity_id TEXT,\n  data_json TEXT NOT NULL DEFAULT '{}',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE TABLE IF NOT EXISTS policies (\n  key TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  body_html TEXT NOT NULL,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "INSERT OR IGNORE INTO policies(key,title,body_html) VALUES\n('privacy','Chính sách quyền riêng tư','<h2>Quyền riêng tư tại SLC</h2><p>SLC chỉ thu thập dữ liệu cần thiết để vận hành tài khoản, lớp học và hỗ trợ. Ảnh xác minh, bài nộp và dữ liệu riêng tư không được công khai mặc định.</p>'),\n('security','Chính sách bảo mật','<h2>Bảo mật tài khoản</h2><p>Không chia sẻ mật khẩu hoặc mã kích hoạt. Hệ thống ghi nhận phiên đăng nhập để hỗ trợ bảo vệ tài khoản.</p>'),\n('terms','Điều khoản sử dụng','<h2>Điều khoản sử dụng</h2><p>Người dùng có trách nhiệm sử dụng SLC đúng mục đích học tập, cộng đồng và quy định của Sky First Network.</p>');"
    ]
  },
  {
    "name": "0002_learning_plus",
    "statements": [
      "CREATE TABLE IF NOT EXISTS learning_units (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  position INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL DEFAULT 'published',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE\n);",
      "CREATE TABLE IF NOT EXISTS lessons (\n  id TEXT PRIMARY KEY,\n  unit_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  body_html TEXT NOT NULL DEFAULT '',\n  source_material_id TEXT,\n  position INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(unit_id) REFERENCES learning_units(id) ON DELETE CASCADE,\n  FOREIGN KEY(source_material_id) REFERENCES materials(id) ON DELETE SET NULL\n);",
      "CREATE TABLE IF NOT EXISTS lesson_progress (\n  lesson_id TEXT NOT NULL,\n  user_id TEXT NOT NULL,\n  progress_percent INTEGER NOT NULL DEFAULT 0,\n  completed_at TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY(lesson_id,user_id),\n  FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE TABLE IF NOT EXISTS quizzes (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  source_material_id TEXT,\n  title TEXT NOT NULL,\n  questions_json TEXT NOT NULL DEFAULT '[]',\n  status TEXT NOT NULL DEFAULT 'draft',\n  created_by TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(source_material_id) REFERENCES materials(id) ON DELETE SET NULL,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT\n);"
    ]
  },
  {
    "name": "0003_public_account_email",
    "statements": [
      "CREATE TABLE IF NOT EXISTS email_logs (\n  id TEXT PRIMARY KEY,\n  to_email TEXT NOT NULL,\n  subject TEXT NOT NULL,\n  status TEXT NOT NULL,\n  provider_message_id TEXT NOT NULL DEFAULT '',\n  error TEXT NOT NULL DEFAULT '',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "CREATE INDEX IF NOT EXISTS idx_email_logs_to_created\nON email_logs(to_email, created_at DESC);",
      "CREATE INDEX IF NOT EXISTS idx_email_logs_status_created\nON email_logs(status, created_at DESC);"
    ]
  },
  {
    "name": "0004_admin_control_center",
    "statements": [
      "CREATE TABLE IF NOT EXISTS system_settings (\n  key TEXT PRIMARY KEY,\n  value TEXT NOT NULL DEFAULT '',\n  updated_by TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "INSERT OR IGNORE INTO system_settings(key,value) VALUES\n('public_intro_title','Một không gian học tập số được xây dựng để đồng hành lâu dài.'),\n('public_intro_text','Trung tâm Học tập Số Sky First Network kết nối lớp học, học liệu, hoạt động trực tuyến, bài tập, kiểm tra và hỗ trợ trong một hành trình thống nhất.'),\n('support_email','support@skyfirst.io.vn'),\n('system_email','slc@skyfirst.io.vn'),\n('account_request_enabled','1'),\n('maintenance_mode','0'),\n('maintenance_message','Hệ thống đang được bảo trì. Vui lòng quay lại sau.'),\n('default_session_days','30');",
      "CREATE TABLE IF NOT EXISTS announcements (\n  id TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  body TEXT NOT NULL,\n  audience TEXT NOT NULL DEFAULT 'all',\n  status TEXT NOT NULL DEFAULT 'draft',\n  starts_at TEXT,\n  ends_at TEXT,\n  created_by TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE INDEX IF NOT EXISTS idx_announcements_status ON announcements(status,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS email_templates (\n  key TEXT PRIMARY KEY,\n  subject TEXT NOT NULL,\n  body_html TEXT NOT NULL,\n  enabled INTEGER NOT NULL DEFAULT 1,\n  updated_by TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "INSERT OR IGNORE INTO email_templates(key,subject,body_html) VALUES\n('account_request_received','[Sky First] Xác nhận tiếp nhận yêu cầu cấp tài khoản',''),\n('account_approved','[Sky First] Kích hoạt tài khoản SFN',''),\n('account_needs_info','[Sky First] Yêu cầu bổ sung thông tin',''),\n('account_rejected','[Sky First] Kết quả yêu cầu cấp tài khoản','');",
      "CREATE TABLE IF NOT EXISTS admin_activity (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  actor_user_id TEXT,\n  action TEXT NOT NULL,\n  detail_json TEXT NOT NULL DEFAULT '{}',\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE INDEX IF NOT EXISTS idx_admin_activity_created ON admin_activity(created_at DESC);"
    ]
  },
  {
    "name": "0005_admin_supercenter",
    "statements": [
      "CREATE TABLE IF NOT EXISTS notification_center (\n  id TEXT PRIMARY KEY,\n  user_id TEXT,\n  title TEXT NOT NULL,\n  body TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT 'info',\n  link TEXT NOT NULL DEFAULT '',\n  is_read INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_notification_center_user ON notification_center(user_id,is_read,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS admin_notes (\n  id TEXT PRIMARY KEY,\n  entity_type TEXT NOT NULL,\n  entity_id TEXT NOT NULL,\n  note TEXT NOT NULL,\n  created_by TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL\n);",
      "CREATE INDEX IF NOT EXISTS idx_admin_notes_entity ON admin_notes(entity_type,entity_id,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS system_jobs (\n  id TEXT PRIMARY KEY,\n  job_type TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'queued',\n  detail_json TEXT NOT NULL DEFAULT '{}',\n  created_by TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  finished_at TEXT,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL\n);",
      "INSERT OR IGNORE INTO system_settings(key,value) VALUES\n('site_name','Trung tâm Học tập Số Sky First Network'),\n('site_name_en','Sky First Network Digital Learning Center'),\n('public_about_title','Không gian học tập số cho hành trình phát triển dài hạn.'),\n('public_about_text','Trung tâm Học tập Số Sky First Network được xây dựng như một không gian học tập và vận hành thống nhất, nơi người học có thể tham gia lớp, tiếp cận học liệu, làm bài tập, kiểm tra, học trực tuyến và nhận hỗ trợ trong cùng một hệ thống.'),\n('allow_guest_live','1'),\n('default_class_unit','Sky First Network'),\n('footer_product_text','Một sản phẩm thuộc hệ sinh thái Sky First Network.'),\n('footer_copyright','© 2026 Sky First Network. Mọi quyền được bảo lưu.');"
    ]
  },
  {
    "name": "0006_v10_hardening",
    "statements": [
      "CREATE TABLE IF NOT EXISTS login_throttle (\n  key TEXT PRIMARY KEY,\n  attempts INTEGER NOT NULL DEFAULT 0,\n  window_started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  blocked_until TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "CREATE TABLE IF NOT EXISTS live_access_tokens (\n  token TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  user_id TEXT,\n  guest_name TEXT NOT NULL DEFAULT '',\n  role TEXT NOT NULL DEFAULT 'guest',\n  expires_at TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_live_access_tokens_class\nON live_access_tokens(class_id,expires_at);",
      "CREATE TABLE IF NOT EXISTS class_messages (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  user_id TEXT NOT NULL,\n  body TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  edited_at TEXT,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE\n);",
      "CREATE INDEX IF NOT EXISTS idx_class_messages_class\nON class_messages(class_id,created_at DESC);",
      "CREATE TABLE IF NOT EXISTS class_events (\n  id TEXT PRIMARY KEY,\n  class_id TEXT NOT NULL,\n  title TEXT NOT NULL,\n  details TEXT NOT NULL DEFAULT '',\n  event_type TEXT NOT NULL DEFAULT 'class',\n  starts_at TEXT NOT NULL,\n  ends_at TEXT,\n  created_by TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,\n  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT\n);",
      "CREATE INDEX IF NOT EXISTS idx_class_events_class\nON class_events(class_id,starts_at);",
      "CREATE TABLE IF NOT EXISTS system_incidents (\n  id TEXT PRIMARY KEY,\n  severity TEXT NOT NULL DEFAULT 'info',\n  component TEXT NOT NULL,\n  message TEXT NOT NULL,\n  detail_json TEXT NOT NULL DEFAULT '{}',\n  resolved_at TEXT,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);",
      "CREATE INDEX IF NOT EXISTS idx_system_incidents_created\nON system_incidents(created_at DESC);",
      "INSERT OR IGNORE INTO system_settings(key,value) VALUES\n('platform_version','V10'),\n('login_rate_limit','10'),\n('max_upload_mb','50'),\n('account_portrait_max_mb','5'),\n('account_document_max_mb','10'),\n('public_status_text','Hệ thống đang hoạt động ổn định.'),\n('live_mesh_max_peers','18');"
    ]
  }
];
